### ISSUE TITLE
Missing f in line 411

### ISSUE THREAD

**Issue by Mr-ZBin** [sanders41/sas7bdat_converter#49]
Hi,

Please update this line, below is my results.

![image](https://user-images.githubusercontent.com/22544491/104438700-41776d80-55cb-11eb-9bd9-224ab6b0e692.png)
![image](https://user-images.githubusercontent.com/22544491/104438759-50f6b680-55cb-11eb-8944-0b8290812245.png)

Thanks

**Comment by sanders41** [comment]
Thanks for this report. I have made the update and published a new version to pypi.
